### ISSUE TITLE
this happens when i run

### ISSUE THREAD

**Issue by malwarekat** [notsniped/discord-snipe-bot#7]
Traceback (most recent call last):
  File "C:\Users\malwarekat\Desktop\discord-snipe-bot-1.2.1\Main.py", line 105, in <module>
    client.run(str(bot_token))
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 601, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001588C4ACEE0>
Traceback (most recent call last):
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__    self.close()
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001588C4ACEE0>
Traceback (most recent call last):
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\malwarekat\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

**Comment by notsniped** [comment]
Actually this is because you forgot to add your bot token. Before running you have to add your Discord bot token inside the `bot_token` variable (line 10).
```py
bot_token = '' ## Add the Discord bot token in this variable. ##
client.run(str(bot_token)) # Wrong! bot_token variable is empty and it will give an error. 
```
If you don't have a token, you can get one from https://discord.com/developers after you make a new app.

**Comment by notsniped** [comment]
```py
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
```

To fix this, you have to go to your bot application in https://discord.com/developers/applications/, then go to **Bot > Priviledged gateway intents** and turn on Presence Intent and Server Members Intent.

![Screenshot_20220717_152211](https://user-images.githubusercontent.com/72265661/179392993-985e8299-a814-498f-a7bf-b2a16add4f9b.png)
